---
- hosts: host1
  remote_user: testadmin
  sudo: yes
  sudo_user: azure-admin
  gather_facts: no
  tasks:
  - name: Install nodejs
    apt: name=nodejs state=present
    become_user: root
  - name: Install Express
    shell: npm install express
    become_user: root