---
- hosts: host1
  remote_user: testadmin
  sudo: yes
  sudo_user: azure-admin
  gather_facts: no
  tasks:
  - name: Install Apache
    apt: name=apache2 state=present
    become_user: root
  - name: Start Apache
    service: name=apache2 state=started
    become_user: root